#!/bin/bash
# Auto-generate stdlib/sys.aria from Linux kernel headers
# Usage: ./scripts/gen-sys-constants.sh > stdlib/sys.aria

HEADER="/usr/include/x86_64-linux-gnu/asm/unistd_64.h"
if [ ! -f "$HEADER" ]; then
    HEADER="/usr/include/asm/unistd_64.h"
fi
if [ ! -f "$HEADER" ]; then
    echo "Error: Cannot find unistd_64.h" >&2
    exit 1
fi

cat << 'HEADER'
// =============================================================================
// sys.aria — Linux x86-64 Syscall Constants
// Auto-generated from kernel headers. Do not edit manually.
// Generated by: scripts/gen-sys-constants.sh
// =============================================================================
//
// These constants are for use with sys!!() and sys!!!() tiers.
// The safe tier sys() uses builtin named constants (READ, WRITE, etc.)
// that are enforced at compile time.
//
// Usage:
//   import sys;
//   Result<int64>:r = sys!!(SYS_FORK);
//   int64:raw = sys!!!(SYS_WRITE, 1, buf, len);

HEADER

grep '^#define __NR_' "$HEADER" | while read -r _ name number; do
    # Convert __NR_foo to SYS_FOO
    constname=$(echo "$name" | sed 's/^__NR_/SYS_/' | tr '[:lower:]' '[:upper:]')
    echo "int64:${constname} = ${number};"
done

echo ""
echo "// Total syscalls: $(grep -c '^#define __NR_' "$HEADER")"
