/**
 * ARIA-024: Limb-Based Integral Model (LBIM) Runtime Intrinsics
 *
 * Implements division and modulo operations for large integers (int128/256/512)
 * using Knuth's Algorithm D for multi-precision division.
 *
 * These operations are too complex to inline and are called by the compiler backend.
 */

#ifndef ARIA_RUNTIME_LBIM_H
#define ARIA_RUNTIME_LBIM_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// ═══════════════════════════════════════════════════════════════════════
// LBIM Type Definitions
// These match the struct layouts generated by the compiler:
//   %struct.int128 = type { [2 x i64] }
//   %struct.int256 = type { [4 x i64] }
//   %struct.int512 = type { [8 x i64] }
//   %struct.int1024 = type { [16 x i64] }  (ARIA-025: Post-quantum crypto)
// ═══════════════════════════════════════════════════════════════════════

typedef struct {
    uint64_t limbs[2];
} npk_int128_t;

typedef struct {
    uint64_t limbs[4];
} npk_int256_t;

typedef struct {
    uint64_t limbs[8];
} npk_int512_t;

typedef struct {
    uint64_t limbs[16];
} npk_int1024_t;

// ═══════════════════════════════════════════════════════════════════════
// int128 Division and Modulo
// ═══════════════════════════════════════════════════════════════════════

/**
 * Unsigned division for int128: quotient = dividend / divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
npk_int128_t npk_lbim_udiv128(npk_int128_t dividend, npk_int128_t divisor);

/**
 * Unsigned modulo for int128: remainder = dividend % divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
npk_int128_t npk_lbim_umod128(npk_int128_t dividend, npk_int128_t divisor);

/**
 * Signed division for int128
 */
npk_int128_t npk_lbim_sdiv128(npk_int128_t dividend, npk_int128_t divisor);

/**
 * Signed modulo for int128
 */
npk_int128_t npk_lbim_smod128(npk_int128_t dividend, npk_int128_t divisor);

// ═══════════════════════════════════════════════════════════════════════
// int256 Division and Modulo
// ═══════════════════════════════════════════════════════════════════════

/**
 * Unsigned division for int256: quotient = dividend / divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
npk_int256_t npk_lbim_udiv256(npk_int256_t dividend, npk_int256_t divisor);

/**
 * Unsigned modulo for int256: remainder = dividend % divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
npk_int256_t npk_lbim_umod256(npk_int256_t dividend, npk_int256_t divisor);

/**
 * Signed division for int256
 */
npk_int256_t npk_lbim_sdiv256(npk_int256_t dividend, npk_int256_t divisor);

/**
 * Signed modulo for int256
 */
npk_int256_t npk_lbim_smod256(npk_int256_t dividend, npk_int256_t divisor);

// ═══════════════════════════════════════════════════════════════════════
// int512 Division and Modulo
// ═══════════════════════════════════════════════════════════════════════

/**
 * Unsigned division for int512: quotient = dividend / divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
npk_int512_t npk_lbim_udiv512(npk_int512_t dividend, npk_int512_t divisor);

/**
 * Unsigned modulo for int512: remainder = dividend % divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
npk_int512_t npk_lbim_umod512(npk_int512_t dividend, npk_int512_t divisor);

/**
 * Signed division for int512
 */
npk_int512_t npk_lbim_sdiv512(npk_int512_t dividend, npk_int512_t divisor);

/**
 * Signed modulo for int512
 */
npk_int512_t npk_lbim_smod512(npk_int512_t dividend, npk_int512_t divisor);

// ═══════════════════════════════════════════════════════════════════════
// int1024 Division and Modulo (ARIA-025: Post-quantum cryptography)
// ═══════════════════════════════════════════════════════════════════════

/**
 * Unsigned division for int1024: quotient = dividend / divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
npk_int1024_t npk_lbim_udiv1024(npk_int1024_t dividend, npk_int1024_t divisor);

/**
 * Unsigned modulo for int1024: remainder = dividend % divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
npk_int1024_t npk_lbim_umod1024(npk_int1024_t dividend, npk_int1024_t divisor);

/**
 * Signed division for int1024
 */
npk_int1024_t npk_lbim_sdiv1024(npk_int1024_t dividend, npk_int1024_t divisor);

/**
 * Signed modulo for int1024
 */
npk_int1024_t npk_lbim_smod1024(npk_int1024_t dividend, npk_int1024_t divisor);

// ═══════════════════════════════════════════════════════════════════════
// Bitwise Operations (int128/256/512/1024)
// Sign-independent: same function for int* and uint* variants.
// ═══════════════════════════════════════════════════════════════════════

npk_int128_t  npk_lbim_and128 (npk_int128_t  a, npk_int128_t  b);
npk_int128_t  npk_lbim_or128  (npk_int128_t  a, npk_int128_t  b);
npk_int128_t  npk_lbim_xor128 (npk_int128_t  a, npk_int128_t  b);
npk_int128_t  npk_lbim_not128 (npk_int128_t  a);

npk_int256_t  npk_lbim_and256 (npk_int256_t  a, npk_int256_t  b);
npk_int256_t  npk_lbim_or256  (npk_int256_t  a, npk_int256_t  b);
npk_int256_t  npk_lbim_xor256 (npk_int256_t  a, npk_int256_t  b);
npk_int256_t  npk_lbim_not256 (npk_int256_t  a);

npk_int512_t  npk_lbim_and512 (npk_int512_t  a, npk_int512_t  b);
npk_int512_t  npk_lbim_or512  (npk_int512_t  a, npk_int512_t  b);
npk_int512_t  npk_lbim_xor512 (npk_int512_t  a, npk_int512_t  b);
npk_int512_t  npk_lbim_not512 (npk_int512_t  a);

npk_int1024_t npk_lbim_and1024(npk_int1024_t a, npk_int1024_t b);
npk_int1024_t npk_lbim_or1024 (npk_int1024_t a, npk_int1024_t b);
npk_int1024_t npk_lbim_xor1024(npk_int1024_t a, npk_int1024_t b);
npk_int1024_t npk_lbim_not1024(npk_int1024_t a);

// ═══════════════════════════════════════════════════════════════════════
// Exponentiation (int128/256/512/1024)
// Binary exponentiation (square-and-multiply). Exponent is unsigned int64.
// Returns ERR sentinel on overflow or if base is ERR.
// ═══════════════════════════════════════════════════════════════════════

npk_int128_t  npk_lbim_pow128 (npk_int128_t  base, uint64_t exp);
npk_int256_t  npk_lbim_pow256 (npk_int256_t  base, uint64_t exp);
npk_int512_t  npk_lbim_pow512 (npk_int512_t  base, uint64_t exp);
npk_int1024_t npk_lbim_pow1024(npk_int1024_t base, uint64_t exp);

// ═══════════════════════════════════════════════════════════════════════
// Shift Operations (int128/256/512/1024)
// Left shift, logical right shift, arithmetic right shift.
// ERR sentinel is preserved through shifts.
// ═══════════════════════════════════════════════════════════════════════

npk_int128_t  npk_lbim_shl128  (npk_int128_t  a, uint32_t shift);
npk_int128_t  npk_lbim_lshr128 (npk_int128_t  a, uint32_t shift);
npk_int128_t  npk_lbim_ashr128 (npk_int128_t  a, uint32_t shift);

npk_int256_t  npk_lbim_shl256  (npk_int256_t  a, uint32_t shift);
npk_int256_t  npk_lbim_lshr256 (npk_int256_t  a, uint32_t shift);
npk_int256_t  npk_lbim_ashr256 (npk_int256_t  a, uint32_t shift);

npk_int512_t  npk_lbim_shl512  (npk_int512_t  a, uint32_t shift);
npk_int512_t  npk_lbim_lshr512 (npk_int512_t  a, uint32_t shift);
npk_int512_t  npk_lbim_ashr512 (npk_int512_t  a, uint32_t shift);

npk_int1024_t npk_lbim_shl1024 (npk_int1024_t a, uint32_t shift);
npk_int1024_t npk_lbim_lshr1024(npk_int1024_t a, uint32_t shift);
npk_int1024_t npk_lbim_ashr1024(npk_int1024_t a, uint32_t shift);

#ifdef __cplusplus
}
#endif

#endif // ARIA_RUNTIME_LBIM_H
