/**
 * ARIA-024: Limb-Based Integral Model (LBIM) Runtime Intrinsics
 *
 * Implements division and modulo operations for large integers (int128/256/512)
 * using Knuth's Algorithm D for multi-precision division.
 *
 * These operations are too complex to inline and are called by the compiler backend.
 */

#ifndef ARIA_RUNTIME_LBIM_H
#define ARIA_RUNTIME_LBIM_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// ═══════════════════════════════════════════════════════════════════════
// LBIM Type Definitions
// These match the struct layouts generated by the compiler:
//   %struct.int128 = type { [2 x i64] }
//   %struct.int256 = type { [4 x i64] }
//   %struct.int512 = type { [8 x i64] }
//   %struct.int1024 = type { [16 x i64] }  (ARIA-025: Post-quantum crypto)
// ═══════════════════════════════════════════════════════════════════════

typedef struct {
    uint64_t limbs[2];
} aria_int128_t;

typedef struct {
    uint64_t limbs[4];
} aria_int256_t;

typedef struct {
    uint64_t limbs[8];
} aria_int512_t;

typedef struct {
    uint64_t limbs[16];
} aria_int1024_t;

// ═══════════════════════════════════════════════════════════════════════
// int128 Division and Modulo
// ═══════════════════════════════════════════════════════════════════════

/**
 * Unsigned division for int128: quotient = dividend / divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
aria_int128_t aria_lbim_udiv128(aria_int128_t dividend, aria_int128_t divisor);

/**
 * Unsigned modulo for int128: remainder = dividend % divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
aria_int128_t aria_lbim_umod128(aria_int128_t dividend, aria_int128_t divisor);

/**
 * Signed division for int128
 */
aria_int128_t aria_lbim_sdiv128(aria_int128_t dividend, aria_int128_t divisor);

/**
 * Signed modulo for int128
 */
aria_int128_t aria_lbim_smod128(aria_int128_t dividend, aria_int128_t divisor);

// ═══════════════════════════════════════════════════════════════════════
// int256 Division and Modulo
// ═══════════════════════════════════════════════════════════════════════

/**
 * Unsigned division for int256: quotient = dividend / divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
aria_int256_t aria_lbim_udiv256(aria_int256_t dividend, aria_int256_t divisor);

/**
 * Unsigned modulo for int256: remainder = dividend % divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
aria_int256_t aria_lbim_umod256(aria_int256_t dividend, aria_int256_t divisor);

/**
 * Signed division for int256
 */
aria_int256_t aria_lbim_sdiv256(aria_int256_t dividend, aria_int256_t divisor);

/**
 * Signed modulo for int256
 */
aria_int256_t aria_lbim_smod256(aria_int256_t dividend, aria_int256_t divisor);

// ═══════════════════════════════════════════════════════════════════════
// int512 Division and Modulo
// ═══════════════════════════════════════════════════════════════════════

/**
 * Unsigned division for int512: quotient = dividend / divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
aria_int512_t aria_lbim_udiv512(aria_int512_t dividend, aria_int512_t divisor);

/**
 * Unsigned modulo for int512: remainder = dividend % divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
aria_int512_t aria_lbim_umod512(aria_int512_t dividend, aria_int512_t divisor);

/**
 * Signed division for int512
 */
aria_int512_t aria_lbim_sdiv512(aria_int512_t dividend, aria_int512_t divisor);

/**
 * Signed modulo for int512
 */
aria_int512_t aria_lbim_smod512(aria_int512_t dividend, aria_int512_t divisor);

// ═══════════════════════════════════════════════════════════════════════
// int1024 Division and Modulo (ARIA-025: Post-quantum cryptography)
// ═══════════════════════════════════════════════════════════════════════

/**
 * Unsigned division for int1024: quotient = dividend / divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
aria_int1024_t aria_lbim_udiv1024(aria_int1024_t dividend, aria_int1024_t divisor);

/**
 * Unsigned modulo for int1024: remainder = dividend % divisor
 * Returns zero if divisor is zero (TBB safety: caller handles ERR)
 */
aria_int1024_t aria_lbim_umod1024(aria_int1024_t dividend, aria_int1024_t divisor);

/**
 * Signed division for int1024
 */
aria_int1024_t aria_lbim_sdiv1024(aria_int1024_t dividend, aria_int1024_t divisor);

/**
 * Signed modulo for int1024
 */
aria_int1024_t aria_lbim_smod1024(aria_int1024_t dividend, aria_int1024_t divisor);

#ifdef __cplusplus
}
#endif

#endif // ARIA_RUNTIME_LBIM_H
